// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {config} from '../models';

export function AddDepartment(arg1:models.Department):Promise<void>;

export function AddEquipment(arg1:models.Equipment):Promise<void>;

export function AddLicense(arg1:models.License):Promise<void>;

export function AddRoom(arg1:models.Room):Promise<void>;

export function AddUser(arg1:models.ResponsibleUser):Promise<void>;

export function Authenticate(arg1:string):Promise<void>;

export function ChangePassword(arg1:string,arg2:string):Promise<void>;

export function DeleteDepartment(arg1:string):Promise<void>;

export function DeleteEquipment(arg1:string):Promise<void>;

export function DeleteLicense(arg1:string):Promise<void>;

export function DeleteRoom(arg1:string):Promise<void>;

export function DeleteUser(arg1:string):Promise<void>;

export function ExitEditMode():Promise<void>;

export function ExportReportToXLSX(arg1:Array<string>):Promise<string>;

export function GetAllData():Promise<models.DataStore>;

export function GetComponentTypes():Promise<Record<models.ComponentType, string>>;

export function GetConfig():Promise<config.Config>;

export function GetEquipment(arg1:string):Promise<models.Equipment>;

export function GetEquipmentTypes():Promise<Record<models.EquipmentType, string>>;

export function HasDataFile():Promise<boolean>;

export function IsEditMode():Promise<boolean>;

export function IsFirstRun():Promise<boolean>;

export function ReloadData():Promise<models.DataStore>;

export function SelectDataFile():Promise<string>;

export function SelectNewDataFile():Promise<string>;

export function SetDataFilePath(arg1:string):Promise<void>;

export function SetupPassword(arg1:string):Promise<void>;

export function UpdateDepartment(arg1:models.Department):Promise<void>;

export function UpdateEquipment(arg1:models.Equipment):Promise<void>;

export function UpdateFloorPlan(arg1:models.FloorPlan):Promise<void>;

export function UpdateLicense(arg1:models.License):Promise<void>;

export function UpdateRoom(arg1:models.Room):Promise<void>;

export function UpdateUser(arg1:models.ResponsibleUser):Promise<void>;
