// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDepartment(arg1) {
  return window['go']['main']['App']['AddDepartment'](arg1);
}

export function AddEquipment(arg1) {
  return window['go']['main']['App']['AddEquipment'](arg1);
}

export function AddLicense(arg1) {
  return window['go']['main']['App']['AddLicense'](arg1);
}

export function AddRoom(arg1) {
  return window['go']['main']['App']['AddRoom'](arg1);
}

export function AddUser(arg1) {
  return window['go']['main']['App']['AddUser'](arg1);
}

export function Authenticate(arg1) {
  return window['go']['main']['App']['Authenticate'](arg1);
}

export function ChangePassword(arg1, arg2) {
  return window['go']['main']['App']['ChangePassword'](arg1, arg2);
}

export function DeleteDepartment(arg1) {
  return window['go']['main']['App']['DeleteDepartment'](arg1);
}

export function DeleteEquipment(arg1) {
  return window['go']['main']['App']['DeleteEquipment'](arg1);
}

export function DeleteLicense(arg1) {
  return window['go']['main']['App']['DeleteLicense'](arg1);
}

export function DeleteRoom(arg1) {
  return window['go']['main']['App']['DeleteRoom'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function ExitEditMode() {
  return window['go']['main']['App']['ExitEditMode']();
}

export function ExportReportToXLSX(arg1) {
  return window['go']['main']['App']['ExportReportToXLSX'](arg1);
}

export function GetAllData() {
  return window['go']['main']['App']['GetAllData']();
}

export function GetComponentTypes() {
  return window['go']['main']['App']['GetComponentTypes']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetEquipment(arg1) {
  return window['go']['main']['App']['GetEquipment'](arg1);
}

export function GetEquipmentTypes() {
  return window['go']['main']['App']['GetEquipmentTypes']();
}

export function HasDataFile() {
  return window['go']['main']['App']['HasDataFile']();
}

export function IsEditMode() {
  return window['go']['main']['App']['IsEditMode']();
}

export function IsFirstRun() {
  return window['go']['main']['App']['IsFirstRun']();
}

export function ReloadData() {
  return window['go']['main']['App']['ReloadData']();
}

export function SelectDataFile() {
  return window['go']['main']['App']['SelectDataFile']();
}

export function SelectNewDataFile() {
  return window['go']['main']['App']['SelectNewDataFile']();
}

export function SetDataFilePath(arg1) {
  return window['go']['main']['App']['SetDataFilePath'](arg1);
}

export function SetupPassword(arg1) {
  return window['go']['main']['App']['SetupPassword'](arg1);
}

export function UpdateDepartment(arg1) {
  return window['go']['main']['App']['UpdateDepartment'](arg1);
}

export function UpdateEquipment(arg1) {
  return window['go']['main']['App']['UpdateEquipment'](arg1);
}

export function UpdateFloorPlan(arg1) {
  return window['go']['main']['App']['UpdateFloorPlan'](arg1);
}

export function UpdateLicense(arg1) {
  return window['go']['main']['App']['UpdateLicense'](arg1);
}

export function UpdateRoom(arg1) {
  return window['go']['main']['App']['UpdateRoom'](arg1);
}

export function UpdateUser(arg1) {
  return window['go']['main']['App']['UpdateUser'](arg1);
}
